@url = http://localhost:8080/api/user

GET {{url}}/4 HTTP/1.1

###
PUT {{url}}/4 HTTP/1.1
Content-Type: application/json

{
  "id": 4,
  "displayName": "PersonalSpaceInvader"
}

###
GET {{url}}/1 HTTP/1.1

###
DELETE {{url}}/1/list-delete/1 HTTP/1.1