@url = http://localhost:8080/api/user

GET {{url}} HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 4
}

###
PUT {{url}} HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 4,
  "displayName": "PersonalSpaceInvader"
}

###
GET {{url}} HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 1
}

###
POST {{url}}/list HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 0,
  "userId": 1,
  "name": "Urgency Groceri",
  "list": [
    {
      "id": 3,
      "name": "Tomato",
      "imageUrl": "https://tomato.com/tomato.jpg",
      "aisle": "Produce"
    },
    {
      "id": 4,
      "name": "Bell Pepper",
      "imageUrl": "http://google.com/pepper.jpg",
      "aisle": "Produce"
    },
    {
      "id": 5,
      "name": "Corn Tortilla",
      "imageUrl": "http://bread.com/bread.jpg",
      "aisle": null
    }
  ]
}

###
PUT {{url}}/list HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 5,
  "userId": 1,
  "name": "Semi Urgent Groceries",
  "list": [
    {
      "id": 3,
      "name": "Tomato",
      "imageUrl": "https://tomato.com/tomato.jpg",
      "aisle": "Produce"
    }
  ]
}

###
DELETE {{url}}/list HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 8,
  "userId": 1
}

###

POST {{url}}/favorite HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "userId": 1,
  "recipeId": 3
}

###

GET {{url}} HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "id": 1
}

###

DELETE  {{url}}/favorite HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
  "userId": 1,
  "recipeId": 3
}